### ISSUE TITLE
Question: log outputs on tests that call std::process::exit()?

### ISSUE THREAD

**Issue by Carter12s** [d-e-s-o/test-log#31]
I have an async tokio test that I'm trying to debug in CI. The test is hanging somewhere until CI reaches maximum time at which point it gets killed. I tried adding an "overall watchdog" to the test like this:

```rust
let _ = tokio::spawn(async {
    tokio::time::sleep(TIMEOUT * 5).await;
    log::error!("Test watchdog tripped!");
    std::process::exit(666);
});
```

But found that if I invoked std::process::exit I didn't get any log output. Obviously there are other ways I can build this watchdog to have the test panic! or bubble up an Err(). But was curious if there was a way to get this crate to log on exit or a clever workaround?

**Comment by d-e-s-o** [comment]
Your problem is that the "Test watchdog tripped!" message is not emitted before the `exit(666)` call? From what I recall one of `tracing` / `log` logs to stdout while the other to stderr. stdout is buffered and unlikely to get flushed on exit. If you force usage of stderr your messages should appear before the exit goes through as it's unbuffered by design.
I don't think this crate provides any trigger/hooks for logging on exit specifically.
